name: Run tests
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with: 
          fetch-depth: 0
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
